<div class="image">

  <img style="float: right;" src="https://pku.org.uk/head.png" width="45%" align="right">
      <h4>
          <p style="font-size:25pt">UK19B307 AI Analytics</p>
          <p style="font-size:15pt">Quiz 4</p>
      </h4>
<h5>
    <p> Peking University</p>
    <p> Demonstrable Labs</p>
</h5>
</div>

### Please doule click this block and enter your name / ID:

- Name: 
- ID: 

In [16]:
import numpy as np
import pandas as pd

<div class="alert alert-warning">
<b>QUESTION 1: </b> 

1, Define a list: `persons = [ "John", "Marissa", "Pete", "Dayton" ]`

2, Print the first two elements by slicing the list. The expected output is: `['John', 'Marissa']`
</div>

In [1]:
persons = [ "John", "Marissa", "Pete", "Dayton" ]
print(persons[0:2])

['John', 'Marissa']


<div class="alert alert-warning">
<b>QUESTION 2: </b> 

Using a `while` loop, print integers from range `25` to `70`. The integers should be divisible by 3. The expected output is:
```
27
30
33
36
39
42
45
48
51
54
57
60
63
66
69```

In [4]:
n=25
while n <= 70:
    n += 1
    if n % 3 == 0:
        print(n)

27
30
33
36
39
42
45
48
51
54
57
60
63
66
69


<div class="alert alert-warning">
<b>QUESTION 3: </b> 

1, Define a list: `list_x = ['7', '1', '2', '5']`
    
2, Use list comprehension to convert the strings in the list to integers. Print the updated list, the expected output is: `[7, 1, 2, 5]`
</div>

In [10]:
results = list(map(int,list_x))
print(results)

[7, 1, 2, 5]


<div class="alert alert-warning">

<b>QUESTION 4:</b>

1, Create a function called `common` that takes two lists as arguments. The function would return a **list** with common characters from the input lists.

2, Define two lists:

```python
list_1 = [1,2,3]
list_2 = [2,3,4]
```
    
3, Call the function with the two lists, print the result, the expected output is: 
 
```
[2, 3]```
 
</div>

In [14]:
def common(x,y):
    list_1=[]
    x = x in list_1
    y = y in list_2
    if x == y:
        list_1.append(x)
list_1 = [1,2,3]
list_2 = [2,3,4]
print(list_1)

[1, 2, 3]


<div class="alert alert-warning">
<b>QUESTION 5:</b> 
    
1, Define an array: `arr_nums = np.array([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21])`
 
2, Calculate the cumulative sum of the array and print the result. The expected output is: `[  1   4   9  16  25  36  49  64  81 100 121]`

</div>

In [18]:
arr_nums = np.array([1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21])
print(arr_nums.cumsum(axis=0))

[  1   4   9  16  25  36  49  64  81 100 121]


<div class="alert alert-warning">
<b>QUESTION 6:</b>
  
Please fill the gaps in the code below so that it prints all the prime&ast; numbers in range from `2` to `50`.

```python
for possiblePrime in _______:
    isPrime = True
    for num in range(2, possiblePrime):
        if possiblePrime % num == 0:
            isPrime = False 
    if _______:
        print(________)  
```
    
&ast; A prime number has to be a positive integer, which is divisible by exactly two integers ($1$ and itself), also $1$ is not a prime number.

The expected output of the code is:
```
2
3
5
7
11
13
17
19
23
29
31
37
41
43
47```
</div>

In [21]:
for possiblePrime in range(2,50):
    isPrime = True
    for num in range(2, possiblePrime):
        if possiblePrime % num == 0:
            isPrime = False 
primes = []
    if isPrime:
        primes.append(possiblePrime)

IndentationError: unexpected indent (<ipython-input-21-9577d1d7e570>, line 7)

<div class="alert alert-warning">
<b>QUESTION 7:</b>
    
1, Define two DataFrames: 

```python
df_1 = pd.DataFrame({'name': ['Jason', 'Tina', 'Jake', 'Amy'],
                     'age': [32, 28, 23, 33],
                     'TestScore': [70, 92, 88, 65]})
df_2 = pd.DataFrame({'name': ['Tim', 'Alice'],
                     'age': [21, 33],
                     'TestScore': [81, 83]})```
    
2, Define a new DataFrame called `df_3` which concatenates `df_1` and `df_2`. Display `df_3`, the expected output is:
    
<img src="//i.imgur.com/KYsFGl9.png" height="20%" width="20%">
</div>

In [25]:
df_1 = pd.DataFrame({'name': ['Jason', 'Tina', 'Jake', 'Amy'],
                     'age': [32, 28, 23, 33],
                     'TestScore': [70, 92, 88, 65]})
df_2 = pd.DataFrame({'name': ['Tim', 'Alice'],
                     'age': [21, 33],
                     'TestScore': [81, 83]})
df_3 = pd.merge(df_1, df_2,how = 'outer')
df_3

name  age  TestScore
0  Jason   32         70
1   Tina   28         92
2   Jake   23         88
3    Amy   33         65
4    Tim   21         81
5  Alice   33         83

<div class="alert alert-warning">
<b>QUESTION 8:</b>
    
Sort the DataFrame `df_3` by column `age`, then by column `TestScore`, both with descending orders. Display the updated DataFrame, the expected output is:

<img src="//i.imgur.com/5sAfdZV.png" height="20%" width="20%">

</div>

In [28]:
df = df_3.sort_values(['age','TestScore'],ascending = False)
df

name  age  TestScore
5  Alice   33         83
3    Amy   33         65
0  Jason   32         70
1   Tina   28         92
2   Jake   23         88
4    Tim   21         81

<div class="alert alert-warning">
<b>QUESTION 9:</b>
    
Create a new column called `group` in `df_3`, the value in the column is `A` if `age` is lager than 30 and `B` otherwise. Display the new DataFrame, the expected output is: 

<img src="//i.imgur.com/nzbxPbi.png" height="20%" width="20%">

</div>

In [31]:
df_3['group'] = df_3['age'] >30
df_3['group'] = df_3['group'].replace({True:'A', False:'B'})
df_3

name  age  TestScore group
0  Jason   32         70     A
1   Tina   28         92     B
2   Jake   23         88     B
3    Amy   33         65     A
4    Tim   21         81     B
5  Alice   33         83     A

<div class="alert alert-warning">
<b>QUESTION 10:</b>
    
Reset the index of `df_3` so that it ranges from 0 to 5. Display the new DataFrame, the expected output is:
    
<img src="//i.imgur.com/Le4KHUu.png" height="20%" width="20%">    

</div>

In [35]:
df_3 = df_3.reindex([range(1,6)]
df_3

name  age  TestScore group
(1, 2, 3, 4, 5)  NaN  NaN        NaN   NaN

<div class="alert alert-warning">
<b>QUESTION 11:</b>
    
1, Define an array: `arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`

2, Extract all odd numbers from `arr` as a array. Print the result, the expected output is: `[1 3 5 7 9]`
</div>

In [39]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
odd = [i for i in arr if i % 2 != 0] 
odd

[1, 3, 5, 7, 9]

<div class="alert alert-warning">
<b>QUESTION 12:</b>
    
Please fill the gaps in the code below so that the output of it would be `LeafRed`.
    
```python
Types = ['Leaf', 'Fire', 'Water']
Colours = ['Green', 'Red', 'Blue']
print('______'.format(Colours[1], Types[0]))
```

</div>

In [42]:
Types = ['Leaf', 'Fire', 'Water']
Colours = ['Green', 'Red', 'Blue']
print('Selection: {1},{0}'.format(Colours[1], Types[0]))

Selection: Leaf,Red


<div class="alert alert-warning">
<b>QUESTION 13:</b>
    
1, Define an array: `arr = np.arange(24).reshape(6,4)`

2, Print the array below by indexing `arr`.

```    
[[ 9 10]
 [13 14]]```

</div>

In [44]:
arr = np.arange(24).reshape(6,4)
arr
print(arr[2:4, 1:3])

[[ 9 10]
 [13 14]]


<div class="alert alert-warning">
<b>QUESTION 14:</b>
    
1, Define a string: `random_str = 'erdXxorPQjFXXyaxoJQI'`

2, Calculate the number of `X` and `x` (upper and lower case letters) in the string and print the result. The expected output is `5`.
</div>

In [46]:
random_str = 'erdXxorPQjFXXyaxoJQI'
'erdXxorPQjFXXyaxoJQI'.count('x') + 'erdXxorPQjFXXyaxoJQI'.count('X')

5

<div class="alert alert-warning">
<b>QUESTION 15: </b> 

1, Define a DataFrame:

```python
customer_data = pd.DataFrame(
    {'customer_id': [3, 2, 9, 4, 5, 8, 10, 1, 15, 11, 6, 7, 12, 14, 13],
     'gender': ['M','F','M','M','F','M','F','F','F','F','F','M','M','M','F'],
     'customer_age': [22, 21, 35, 40, 22, 28, 25, 43, 33, 37, 27, 30, 20, 50, 32],
     'post_code': ['85711','84623','88282','85732','88200','42610','85790','84600','84686','42699','88211','42671',
                  '42677','85723','88296'],
     'occupation': ['engineer','librarian','lawyer','scientist','engineer','librarian','artist','engineer','lawyer',
                    'artist','engineer','lawyer','librarian','engineer','scientist'],
     'salary': [np.nan, 23000, 45000, 80000, np.nan, 25000, 30000, 22000, 60000, 43000, 33000, 38000,
                20000, 70000, 45000]})
```

2, Fill the missing value in column `salary` with the **median**. 
 
3, Display the DataFrame, the expected output would be:
    
<img src="//i.imgur.com/U8j3p0A.png" height="40%" width="40%">
</div>

In [47]:
customer_data = pd.DataFrame(
    {'customer_id': [3, 2, 9, 4, 5, 8, 10, 1, 15, 11, 6, 7, 12, 14, 13],
     'gender': ['M','F','M','M','F','M','F','F','F','F','F','M','M','M','F'],
     'customer_age': [22, 21, 35, 40, 22, 28, 25, 43, 33, 37, 27, 30, 20, 50, 32],
     'post_code': ['85711','84623','88282','85732','88200','42610','85790','84600','84686','42699','88211','42671',
                  '42677','85723','88296'],
     'occupation': ['engineer','librarian','lawyer','scientist','engineer','librarian','artist','engineer','lawyer',
                    'artist','engineer','lawyer','librarian','engineer','scientist'],
     'salary': [np.nan, 23000, 45000, 80000, np.nan, 25000, 30000, 22000, 60000, 43000, 33000, 38000,
                20000, 70000, 45000]})
customer_data['salary'] = customer_data['salary'].fillna(customer_data['salary'].median())
customer_data

customer_id gender  customer_age post_code occupation   salary
0             3      M            22     85711   engineer  38000.0
1             2      F            21     84623  librarian  23000.0
2             9      M            35     88282     lawyer  45000.0
3             4      M            40     85732  scientist  80000.0
4             5      F            22     88200   engineer  38000.0
5             8      M            28     42610  librarian  25000.0
6            10      F            25     85790     artist  30000.0
7             1      F            43     84600   engineer  22000.0
8            15      F            33     84686     lawyer  60000.0
9            11      F            37     42699     artist  43000.0
10            6      F            27     88211   engineer  33000.0
11            7      M            30     42671     lawyer  38000.0
12           12      M            20     42677  librarian  20000.0
13           14      M            50     85723   engineer  70000.0
14           13      F            32     88296  scientist  45000.0

<div class="alert alert-warning">
<b>QUESTION 16: </b> 

1, Sort the DataFrame `customer_data` by column `customer_id` with ascending order. Then set the column `customer_id` as the index column. 

2, Display the **updated** DataFrame `customer_data`, the expected output would be:
    
<img src="//i.imgur.com/g4svghT.png" height="40%" width="40%">

</div>

In [56]:
customer_data.sort_values('customer_id', ascending=True, inplace=True)
customer_data.index = customer_data['customer_id']
customer_data

customer_id gender  customer_age post_code occupation   salary
customer_id                                                                
1                      1      F            43     84600   engineer  22000.0
2                      2      F            21     84623  librarian  23000.0
3                      3      M            22     85711   engineer  38000.0
4                      4      M            40     85732  scientist  80000.0
5                      5      F            22     88200   engineer  38000.0
6                      6      F            27     88211   engineer  33000.0
7                      7      M            30     42671     lawyer  38000.0
8                      8      M            28     42610  librarian  25000.0
9                      9      M            35     88282     lawyer  45000.0
10                    10      F            25     85790     artist  30000.0
11                    11      F            37     42699     artist  43000.0
12                    12      M            20     42677  librarian  20000.0
13                    13      F            32     88296  scientist  45000.0
14                    14      M            50     85723   engineer  70000.0
15                    15      F            33     84686     lawyer  60000.0

<div class="alert alert-warning">
<b>QUESTION 17:</b>

1, Add `2` to each value in column `customer_age` from DataFrame `customer_data`.

2, Display the **updated** DataFrame `customer_data`, the expected output would be:
    
<img src="//i.imgur.com/LeBlTzE.png" height="40%" width="40%">

</div>

In [60]:
customer_data['customer_age']= customer_data.loc[customer_data['customer_age']] = customer_data['customer_age']+2

KeyError: "None of [Int64Index([47, 25, 26, 44, 26, 31, 34, 32, 39, 29, 41, 24, 36, 54, 37], dtype='int64', name='customer_id')] are in the [index]"

<div class="alert alert-warning">
<b>QUESTION 18: </b> 

Display the matching rows in DataFrame `customer_data` where `post_code` start with `88`, the expected output would be:
    
<img src="//i.imgur.com/Kok6yyu.png" height="40%" width="40%">

</div>
</div>

In [64]:
customer_data.loc[customer_data['post_code'].startwith('88')]
customer_data

SyntaxError: unexpected EOF while parsing (<ipython-input-64-5abb10d6b706>, line 3)

<div class="alert alert-warning">
<b>QUESTION 19: </b> 

1, Calculate the average customer age for each occupation based on DataFrame `customer_data`. 

2, Create a DataFrame called `occupation_age` which has index `occupation` and column `customer_age` with the result from step 1. Display the DataFrame `occupation_age`, the expected output would be:
    
<img src="//i.imgur.com/ynMBXbS.png" height="20%" width="20%">
</div>

In [69]:
customer_age_av = customer_data.groupby('occupation')['customer_age'].mean()

TypeError: 'Series' objects are mutable, thus they cannot be hashed

<div class="alert alert-warning">
<b>QUESTION 20:</b>

1, Create a new DataFrame called `customer_data_2` which contains rows from DataFrame `customer_data` where `customer_age` are larger or equal to 30.

2, Display the DataFrame `customer_data_2`, the expected output would be:
    
<img src="https://i.imgur.com/GdNsqyC.png" height="40%" width="40%">
</div>

In [71]:
customer_data_2 = customer_data.customer_age >=30
